import type { Metadata } from "next";
import { Urbanist, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],  // Choose weights you need
  variable: '--font-poppins'  // CSS variable name
})

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-urbanist'
})

export const metadata: Metadata = {
  title: "Jasa buat website cepat dan aman buat bisnis kamu - Seier Tech Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${urbanist.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
